database:
  host: 127.0.0.1
  username: mychunkland
  password: ""
  schema: your_schema

setting:
  default:
    update-block-without-owning: true
    protect-y-range:
#      min: 50
#      max: 200
  worlds:
#     WorldFolderName:
#       update-block-without-owning: false